name: C CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_program
        path: my_program

